version: "3.7"
services:

  sandbox_minapiserver_20240601:
    build:
      context: ./..
      dockerfile: ./docker_windows/dockerfile
    image: sandbox_minapiserver_20240601
    container_name: sandbox_minapiserver_20240601
    ports:
      - '5201:5201'
