FROM mcr.microsoft.com/dotnet/sdk:7.0 AS builder

#SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
# pwsh is not installed in '4.8-windowsservercore-ltsc2019' image
SHELL [ "pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue'; "]

ENV BUILDER_BIN_PATH=c:/_build_bin
ENV BUILDER_SRC_PATH=c:/_build_src
WORKDIR $BUILDER_SRC_PATH
COPY ./ ./
RUN dotnet publish "./MinApiServer.csproj" -c Debug -o "${env:BUILDER_BIN_PATH}" /p:UseAppHost=true

FROM mcr.microsoft.com/dotnet/aspnet:7.0

ENV BUILDER_BIN_PATH=c:/_build_bin
ENV BIN_PATH=c:/_bin
WORKDIR $BIN_PATH
COPY --from=builder "${BUILDER_BIN_PATH}" .

EXPOSE 5201

ENTRYPOINT MinApiServer.exe
#ENTRYPOINT ping -t localhost