trigger:
  branches:
    exclude:
    - '*'

variables:
  DockerfileFolder: '/MyProject/src/docker'
  DockerfileFullPath: '$(DockerfileFolder)/dockerfile'
  MyDockerRegistryServiceConnection: 'hub-docker-com-myconnection'
  HubDockerComRepository: 'mydockerhub/myproject'

stages:

- stage: build_publish_image_stage
  jobs:
  - job: build_publish_image_job
    pool:
      vmImage: 'windows-2019'

    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'MyDBBuildProject'
        definition: 'MyDBBuildProject'
        buildVersionToDownload: 'latest'
        artifactName: 'mydb'
        targetPath: '$(Build.SourcesDirectory)/$(DockerfileFolder)'

    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: $(MyDockerRegistryServiceConnection)

    - task: Docker@2
      displayName: 'Build image'
      inputs:
        command: 'build'
        containerRegistry: '$(MyDockerRegistryServiceConnection)'
        repository: '$(HubDockerComRepository)'
        Dockerfile: '$(DockerfileFullPath)'
        buildContext: '$(DockerfileFolder)'
        tags: 'mydb-windows'

    - task: Docker@2
      displayName: 'Push image'
      inputs:
        command: 'push'
        containerRegistry: '$(MyDockerRegistryServiceConnection)'
        repository: '$(HubDockerComRepository)'
        tags: 'mydb-windows'

    - task: Docker@2
      displayName: Logout of Docker Hub
      inputs:
        command: logout
        containerRegistry: $(MyDockerRegistryServiceConnection)
