version: "3.7"
services:

  sandbox_minapiserver_20240601:
    build:
      context: ./../MinApiServer
      dockerfile: ./docker_windows/dockerfile
    image: sandbox_minapiserver_20240601
    container_name: sandbox_minapiserver_20240601
    ports:
      - '5201:5201'

  sandbox_minapiclient_20240601:
    build:
      context: ./../MinApiClient
      dockerfile: ./docker_windows/dockerfile
    image: sandbox_minapiclient_20240601
    container_name: sandbox_minapiclient_20240601
    depends_on:
      sandbox_minapiserver_20240601:
        condition: service_started
