version: "3.7"

services:
  serverdxindockerapp:
    build:
      no_cache: true
      context: ./..
      dockerfile: ./docker_dev_windows/build.image.release_config.dockerfile
      # docker file can be inlined: https://docs.docker.com/compose/compose-file/build/#dockerfile_inline
      # but it doesn't work in my env ('no docker file' error occurs), there is a similar issue at https://github.com/microsoft/vscode-remote-release/issues/8445
    image: server-dx-in-docker
    container_name: ServerDxInDocker
    ports:
      - 8000:80
