name: BEM/validate-bem tests
on:
  push:
    paths: 
      - 'BEM/validate-bem/**'
  pull_request:
    paths: 
      - 'BEM/validate-bem/**'

env:
  FORCE_COLOR: 2
jobs:
  full:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BEM/validate-bem/
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
