name: CSS/PostCSS Plugin1 tests
on:
  push:
    paths: 
      - 'CSS/PostCSS/postcss-plugin1/**'
  pull_request:
    paths: 
      - 'CSS/PostCSS/postcss-plugin1/**'

env:
  FORCE_COLOR: 2
jobs:
  full:
    name: Node.js 15 Full
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CSS/PostCSS/postcss-plugin1/
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # - name: Install dependencies
      #   uses: bahmutov/npm-install@v1
      # ---- Error: ENOENT: no such file or directory, open '/home/runner/work/Sandbox/Sandbox/package-lock.json'
      - name: install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
          - 12
          - 10
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run unit tests
        run: npx jest
